### ISSUE TITLE
broken dag (prototype.py)

### ISSUE THREAD

**Issue by rochdiD** [rochdiD/Streaming-league-of-legends-data#1]
Broken DAG: [/opt/airflow/dags/prototype.py] Traceback (most recent call last):
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/data/summoners/player_name/id_tracker.csv'

>> the problem is at the postgresOperator, at "sql=insertNewValuesFromCSV(tracker_id,...)"
while being parsed the function can't be rendered because the tracker_id file doesn't exist at parsing time...
>> probable solution, use pythonOperator to avoid rendering the function  before parsing

**Comment by rochdiD** [comment]
use pythonOperator to avoid rendering the function before parsing
